menu:
    Blog: /
    Archive: /archives/
    N-book: //nirodu.com/n-book
    GitHub: https://github.com/nirodu
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
# ga: UA-xxxxxxxx-x

# Copyright Infomation
startyear: 2016
